const { run, get } = require("../../src/models/db");

const knowledgePoints4 = [
  { name: "亿以内数的认识", grade: 4, chapter: "大数的认识", unit: 1 },
  { name: "数位顺序表", grade: 4, chapter: "大数的认识", unit: 1 },
  { name: "读亿以内的数", grade: 4, chapter: "大数的认识", unit: 1 },
  { name: "写亿以内的数", grade: 4, chapter: "大数的认识", unit: 1 },
  { name: "比较数的大小", grade: 4, chapter: "大数的认识", unit: 1 },
  { name: "改写为用\"万\"作单位的数", grade: 4, chapter: "大数的认识", unit: 1 },
  { name: "近似数", grade: 4, chapter: "大数的认识", unit: 1 },
  { name: "十进制计数法", grade: 4, chapter: "大数的认识", unit: 2 },
  { name: "角的度量", grade: 4, chapter: "角的度量", unit: 1 },
  { name: "线段、直线、射线", grade: 4, chapter: "角的度量", unit: 1 },
  { name: "角的分类", grade: 4, chapter: "角的度量", unit: 1 },
  { name: "平行与垂直", grade: 4, chapter: "平行四边形和梯形", unit: 1 },
  { name: "平行四边形的认识", grade: 4, chapter: "平行四边形和梯形", unit: 1 },
  { name: "梯形的认识", grade: 4, chapter: "平行四边形和梯形", unit: 1 },
  { name: "口算乘法", grade: 4, chapter: "三位数乘两位数", unit: 1 },
  { name: "笔算乘法", grade: 4, chapter: "三位数乘两位数", unit: 1 },
  { name: "积的变化规律", grade: 4, chapter: "三位数乘两位数", unit: 1 },
  { name: "路程、时间与速度", grade: 4, chapter: "三位数乘两位数", unit: 1 },
  { name: "条形统计图", grade: 4, chapter: "统计", unit: 1 },
  { name: "优化问题", grade: 4, chapter: "数学广角", unit: 1 },
  { name: "沏茶问题", grade: 4, chapter: "数学广角", unit: 1 },
  { name: "烙饼问题", grade: 4, chapter: "数学广角", unit: 1 },
  { name: "排队问题", grade: 4, chapter: "数学广角", unit: 1 },
  { name: "乘法估算", grade: 4, chapter: "大数的认识", unit: 2 },
  { name: "四舍五入法", grade: 4, chapter: "大数的认识", unit: 2 },
  { name: "加法交换律", grade: 4, chapter: "运算定律", unit: 1 },
  { name: "加法结合律", grade: 4, chapter: "运算定律", unit: 1 },
  { name: "乘法交换律", grade: 4, chapter: "运算定律", unit: 1 },
  { name: "乘法结合律", grade: 4, chapter: "运算定律", unit: 1 },
  { name: "乘法分配律", grade: 4, chapter: "运算定律", unit: 1 },
  { name: "三角形", grade: 4, chapter: "三角形", unit: 1 },
  { name: "三角形的特性", grade: 4, chapter: "三角形", unit: 1 },
  { name: "三角形的分类", grade: 4, chapter: "三角形", unit: 1 },
  { name: "三角形的内角和", grade: 4, chapter: "三角形", unit: 1 },
  { name: "图形的拼组", grade: 4, chapter: "三角形", unit: 1 },
  { name: "小数的意义", grade: 4, chapter: "小数的意义和性质", unit: 1 },
  { name: "小数的读写", grade: 4, chapter: "小数的意义和性质", unit: 1 },
  { name: "小数的性质", grade: 4, chapter: "小数的意义和性质", unit: 1 },
  { name: "小数的大小比较", grade: 4, chapter: "小数的意义和性质", unit: 1 },
  { name: "小数点移动引起小数大小的变化", grade: 4, chapter: "小数的意义和性质", unit: 1 },
  { name: "单位换算", grade: 4, chapter: "小数的意义和性质", unit: 1 },
  { name: "小数加减法", grade: 4, chapter: "小数的加法和减法", unit: 1 },
  { name: "小数加减混合运算", grade: 4, chapter: "小数的加法和减法", unit: 1 },
];

const knowledgePoints5 = [
  { name: "小数乘法", grade: 5, chapter: "小数乘法", unit: 1 },
  { name: "积的近似值", grade: 5, chapter: "小数乘法", unit: 1 },
  { name: "连乘、乘加、乘减", grade: 5, chapter: "小数乘法", unit: 1 },
  { name: "简便计算", grade: 5, chapter: "小数乘法", unit: 1 },
  { name: "小数除法", grade: 5, chapter: "小数除法", unit: 1 },
  { name: "除数是整数的小数除法", grade: 5, chapter: "小数除法", unit: 1 },
  { name: "除数是小数的小数除法", grade: 5, chapter: "小数除法", unit: 1 },
  { name: "商的近似值", grade: 5, chapter: "小数除法", unit: 1 },
  { name: "循环小数", grade: 5, chapter: "小数除法", unit: 1 },
  { name: "用计算器探索规律", grade: 5, chapter: "小数除法", unit: 1 },
  { name: "用字母表示数", grade: 5, chapter: "简易方程", unit: 1 },
  { name: "方程的意义", grade: 5, chapter: "简易方程", unit: 1 },
  { name: "解简易方程", grade: 5, chapter: "简易方程", unit: 1 },
  { name: "解方程", grade: 5, chapter: "简易方程", unit: 1 },
  { name: "列方程解决实际问题", grade: 5, chapter: "简易方程", unit: 1 },
  { name: "位置", grade: 5, chapter: "位置", unit: 1 },
  { name: "数对", grade: 5, chapter: "位置", unit: 1 },
  { name: "多边形的面积", grade: 5, chapter: "多边形的面积", unit: 1 },
  { name: "平行四边形的面积", grade: 5, chapter: "多边形的面积", unit: 1 },
  { name: "三角形的面积", grade: 5, chapter: "多边形的面积", unit: 1 },
  { name: "梯形的面积", grade: 5, chapter: "多边形的面积", unit: 1 },
  { name: "组合图形的面积", grade: 5, chapter: "多边形的面积", unit: 1 },
  { name: "可能性", grade: 5, chapter: "可能性", unit: 1 },
  { name: "掷骰子游戏", grade: 5, chapter: "可能性", unit: 1 },
  { name: "摸球游戏", grade: 5, chapter: "可能性", unit: 1 },
  { name: "植树问题", grade: 5, chapter: "数学广角", unit: 1 },
  { name: "鸡兔同笼", grade: 5, chapter: "数学广角", unit: 1 },
  { name: "抽屉原理", grade: 5, chapter: "数学广角", unit: 1 },
  { name: "分数意义", grade: 5, chapter: "分数意义和性质", unit: 1 },
  { name: "分数与除法", grade: 5, chapter: "分数意义和性质", unit: 1 },
  { name: "真分数和假分数", grade: 5, chapter: "分数意义和性质", unit: 1 },
  { name: "分数的基本性质", grade: 5, chapter: "分数意义和性质", unit: 1 },
  { name: "约分", grade: 5, chapter: "分数意义和性质", unit: 1 },
  { name: "通分", grade: 5, chapter: "分数意义和性质", unit: 1 },
  { name: "分数和小数的互化", grade: 5, chapter: "分数意义和性质", unit: 1 },
  { name: "同分母分数加减法", grade: 5, chapter: "分数的加法和减法", unit: 1 },
  { name: "异分母分数加减法", grade: 5, chapter: "分数的加法和减法", unit: 1 },
  { name: "分数加减混合运算", grade: 5, chapter: "分数的加法和减法", unit: 1 },
  { name: "找次品", grade: 5, chapter: "数学广角", unit: 1 },
];

const knowledgePoints6 = [
  { name: "分数乘法", grade: 6, chapter: "分数乘法", unit: 1 },
  { name: "分数乘整数", grade: 6, chapter: "分数乘法", unit: 1 },
  { name: "分数乘分数", grade: 6, chapter: "分数乘法", unit: 1 },
  { name: "分数混合运算", grade: 6, chapter: "分数乘法", unit: 1 },
  { name: "分数乘法的简便运算", grade: 6, chapter: "分数乘法", unit: 1 },
  { name: "倒数的认识", grade: 6, chapter: "分数乘法", unit: 1 },
  { name: "分数除法", grade: 6, chapter: "分数除法", unit: 1 },
  { name: "分数除以整数", grade: 6, chapter: "分数除法", unit: 1 },
  { name: "一个数除以分数", grade: 6, chapter: "分数除法", unit: 1 },
  { name: "分数混合运算", grade: 6, chapter: "分数除法", unit: 1 },
  { name: "比的认识", grade: 6, chapter: "比", unit: 1 },
  { name: "比的基本性质", grade: 6, chapter: "比", unit: 1 },
  { name: "比的应用", grade: 6, chapter: "比", unit: 1 },
  { name: "圆的认识", grade: 6, chapter: "圆", unit: 1 },
  { name: "圆的周长", grade: 6, chapter: "圆", unit: 1 },
  { name: "圆的面积", grade: 6, chapter: "圆", unit: 1 },
  { name: "扇形", grade: 6, chapter: "圆", unit: 1 },
  { name: "百分数的意义", grade: 6, chapter: "百分数", unit: 1 },
  { name: "百分数和分数的互化", grade: 6, chapter: "百分数", unit: 1 },
  { name: "百分数和小数的互化", grade: 6, chapter: "百分数", unit: 1 },
  { name: "百分数的应用", grade: 6, chapter: "百分数", unit: 1 },
  { name: "折扣问题", grade: 6, chapter: "百分数", unit: 1 },
  { name: "纳税问题", grade: 6, chapter: "百分数", unit: 1 },
  { name: "利率问题", grade: 6, chapter: "百分数", unit: 1 },
  { name: "扇形统计图", grade: 6, chapter: "统计", unit: 1 },
  { name: "圆柱的认识", grade: 6, chapter: "圆柱与圆锥", unit: 1 },
  { name: "圆柱的表面积", grade: 6, chapter: "圆柱与圆锥", unit: 1 },
  { name: "圆柱的体积", grade: 6, chapter: "圆柱与圆锥", unit: 1 },
  { name: "圆锥的认识", grade: 6, chapter: "圆柱与圆锥", unit: 1 },
  { name: "圆锥的体积", grade: 6, chapter: "圆柱与圆锥", unit: 1 },
  { name: "比例的意义", grade: 6, chapter: "比例", unit: 1 },
  { name: "比例的基本性质", grade: 6, chapter: "比例", unit: 1 },
  { name: "解比例", grade: 6, chapter: "比例", unit: 1 },
  { name: "正比例", grade: 6, chapter: "比例", unit: 1 },
  { name: "反比例", grade: 6, chapter: "比例", unit: 1 },
  { name: "比例尺", grade: 6, chapter: "比例", unit: 1 },
  { name: "图形的放大与缩小", grade: 6, chapter: "比例", unit: 1 },
  { name: "数与代数", grade: 6, chapter: "整理和复习", unit: 1 },
  { name: "图形与几何", grade: 6, chapter: "整理和复习", unit: 1 },
  { name: "统计与概率", grade: 6, chapter: "整理和复习", unit: 1 },
  { name: "数学广角", grade: 6, chapter: "数学广角", unit: 1 },
  { name: "鸽巢问题", grade: 6, chapter: "数学广角", unit: 1 },
];

async function seedKnowledgePoints() {
  await run("DELETE FROM knowledge_points");
  let inserted = 0;
  const allPoints = knowledgePoints4.concat(knowledgePoints5).concat(knowledgePoints6);
  for (const kp of allPoints) {
    const id = "kp_" + kp.grade + "_" + kp.chapter.replace(/[^a-zA-Z0-9]/g, "") + "_" + inserted;
    await run("INSERT OR IGNORE INTO knowledge_points (id, name, grade, subject, chapter, unit, difficulty, created_at) VALUES (?, ?, ?, 'math', ?, ?, 0.5, datetime('now'))", [id, kp.name, kp.grade, kp.chapter, kp.unit]);
    inserted++;
  }
  console.log("Seeded " + inserted + " knowledge points");
  return { inserted: inserted };
}

module.exports = { seedKnowledgePoints };
