var fs = require('fs');
var content = 'const initSqlJs = require(\'sql.js\');\n';
content += 'const path = require(\'path\');\n';
content += 'const fs = require(\'fs\');\n\n';
content += 'let db = null;\n\n';
content += 'async function initDatabase(dbPath) {\n';
content += '  const SQL = await initSqlJs();\n';
content += '  try {\n';
content += '    if (fs.existsSync(dbPath)) {\n';
content += '      const fileBuffer = fs.readFileSync(dbPath);\n';
content += '      db = new SQL.Database(fileBuffer);\n';
content += '      console.log(\'Database loaded from \' + dbPath);\n';
content += '    } else {\n';
content += '      db = new SQL.Database();\n';
content += '      console.log(\'New database created\');\n';
content += '    }\n';
content += '  } catch (err) {\n';
content += '    db = new SQL.Database();\n';
content += '    console.log(\'Created new database\');\n';
content += '  }\n';
content += '  return db;\n';
content += '}\n\n';
content += 'function getDb() {\n';
content += '  if (!db) throw new Error(\'Database not initialized\');\n';
content += '  return db;\n';
content += '}\n\n';
content += 'function saveDatabase() {\n';
content += '  if (!db) return;\n';
content += '  const data = db.export();\n';
content += '  const dbPath = process.env.DATABASE_PATH || \'./data/db.sqlite\';\n';
content += '  const dir = path.dirname(dbPath);\n';
content += '  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });\n';
content += '  fs.writeFileSync(dbPath, Buffer.from(data));\n';
content += '}\n\n';
content += 'function query(sql, params) {\n';
content += '  params = params || [];\n';
content += '  const db = getDb();\n';
content += '  const stmt = db.prepare(sql);\n';
content += '  stmt.bind(params);\n';
content += '  const columns = [];\n';
content += '  const rows = [];\n';
content += '  while (stmt.step()) {\n';
content += '    const row = {};\n';
content += '    if (columns.length === 0) {\n';
content += '      for (var i = 0; i < stmt.numColumns(); i++) {\n';
content += '        columns.push(stmt.getColumnName(i));\n';
content += '      }\n';
content += '    }\n';
content += '    for (var i = 0; i < columns.length; i++) {\n';
content += '      row[columns[i]] = stmt.get(i);\n';
content += '    }\n';
content += '    rows.push(row);\n';
content += '  }\n';
content += '  stmt.free();\n';
content += '  return rows;\n';
content += '}\n\n';
content += 'function run(sql, params) {\n';
content += '  params = params || [];\n';
content += '  const db = getDb();\n';
content += '  const stmt = db.prepare(sql);\n';
content += '  stmt.bind(params);\n';
content += '  while (stmt.step()) {}\n';
content += '  stmt.free();\n';
content += '  saveDatabase();\n';
content += '}\n\n';
content += 'module.exports = { initDatabase, getDb, saveDatabase, query, run };\n';
fs.writeFileSync('E:/360MoveData/Users/admin/Documents/小学数学自测及辅导/workspace/web/server/src/models/db.js', content, 'utf8');
console.log('db.js written, length:', content.length);
